package com.civicpulse.service;
import com.civicpulse.dto.ComplaintDtos.*; import com.civicpulse.entity.*; import com.civicpulse.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class ComplaintService {private final ComplaintRepository complaints;private final CategoryRepository categories;private final UserRepository users;private final StatusHistoryRepository history;private final AssignmentRepository assignments;private final NotificationService notifications;private final ResolutionVerificationRepository verifications;public ComplaintService(ComplaintRepository c,CategoryRepository cat,UserRepository u,StatusHistoryRepository h,AssignmentRepository a,NotificationService n,ResolutionVerificationRepository v){complaints=c;categories=cat;users=u;history=h;assignments=a;notifications=n;verifications=v;}
@Transactional public Complaint create(CreateComplaintRequest r,User citizen){Category cat=categories.findById(r.categoryId()).orElseThrow(()->new IllegalArgumentException("Category not found"));Complaint c=new Complaint();c.setCitizen(citizen);c.setCategory(cat);c.setDepartment(cat.getDepartment());c.setTitle(r.title().trim());c.setDescription(r.description().trim());c.setLatitude(r.latitude());c.setLongitude(r.longitude());c.setAddress(r.address());c.setPriority(r.priority()==null?Priority.MEDIUM:r.priority());c.setDueAt(Instant.now().plus(Duration.ofHours(cat.getDefaultSlaHours())));c=complaints.save(c);addHistory(c,null,ComplaintStatus.REPORTED,citizen,"Complaint created");return c;}
public List<Complaint> mine(User u){return complaints.findByCitizenUserIdOrderByCreatedAtDesc(u.getUserId());} public List<Complaint> all(){return complaints.findAllByOrderByCreatedAtDesc();} public Complaint get(UUID id,User viewer){Complaint c=complaints.findById(id).orElseThrow(); if(viewer.getRole()==Role.CITIZEN && !c.getCitizen().getUserId().equals(viewer.getUserId())) throw new SecurityException("Not authorized to view this complaint"); return c;}
@Transactional public Complaint status(UUID id,UpdateStatusRequest r,User actor){Complaint c=complaints.findById(id).orElseThrow();ComplaintStatus old=c.getStatus();c.setStatus(r.status());c.setUpdatedAt(Instant.now());complaints.save(c);addHistory(c,old,r.status(),actor,r.remarks());notifications.notify(c.getCitizen(),c,"Complaint updated","Complaint "+id+" changed to "+r.status()+".");return c;}
@Transactional public Complaint setPriority(UUID id,Priority priority,User actor){Complaint c=complaints.findById(id).orElseThrow();c.setPriority(priority);c.setUpdatedAt(Instant.now());return complaints.save(c);}
@Transactional public Complaint assign(UUID id,AssignRequest r,User officer){Complaint c=complaints.findById(id).orElseThrow();User worker=users.findById(r.workerId()).orElseThrow();if(worker.getRole()!=Role.FIELD_WORKER)throw new IllegalArgumentException("User is not a field worker");Assignment a=assignments.findByComplaintComplaintId(id).orElseGet(Assignment::new);a.setComplaint(c);a.setWorker(worker);a.setAssignedBy(officer);a.setAssignedAt(Instant.now());assignments.save(a);notifications.notify(worker,c,"New task assigned","You have been assigned complaint "+id+".");return status(id,new UpdateStatusRequest(ComplaintStatus.ASSIGNED,"Assigned to field worker"),officer);}
@Transactional public void verify(UUID id,VerifyRequest r,User citizen){Complaint c=complaints.findById(id).orElseThrow();if(!c.getCitizen().getUserId().equals(citizen.getUserId()))throw new SecurityException("Not complaint owner");ResolutionVerification v=new ResolutionVerification();v.setComplaint(c);v.setCitizen(citizen);v.setResult(r.result().toUpperCase());v.setComment(r.comment());verifications.save(v);if(v.getResult().equals("YES")||v.getResult().equals("RESOLVED"))status(id,new UpdateStatusRequest(ComplaintStatus.VERIFIED,"Citizen verified resolution"),citizen);else if(v.getResult().equals("NO")||v.getResult().equals("NOT_RESOLVED")||v.getResult().equals("PARTIALLY_RESOLVED"))status(id,new UpdateStatusRequest(ComplaintStatus.REOPENED,"Citizen reported issue unresolved or partial"),citizen);}
private void addHistory(Complaint c,ComplaintStatus old,ComplaintStatus now,User actor,String remarks){StatusHistory h=new StatusHistory();h.setComplaint(c);h.setOldStatus(old);h.setNewStatus(now);h.setChangedBy(actor);h.setRemarks(remarks);history.save(h);}}
